# to run docker run ID npm run test
language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t stephaniegoldman12/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephaniegoldman12/docker-react npm run test

#tell travis CI where to auto-deploy
deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'Docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-318700323508'
  bucket_path: 'Docker' #equal to app name by default
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
